/* Shared presentation and two-pet household rules, used by both entry points. */
window.PetLife=(()=>{
 const stage=p=>p.temporaryRegression?2:Number(p.stage||0);
 const voices={brave:['멍멍!','멍~!','왈! 왈!','히응…'],careful:['뀨우…','뀨!','응~ 끼잉.','뀨우!'],wise:['캥!','캥~','끼웅…','캥캥!'],kind:['뀨!','우웅~','뀨뀨!','웅…']};
 const young={neutral:['오늘 뭐 해?','나랑 같이 있어 줘.','이거 봐 봐!'],hungry:['배에서 꼬르륵 해.','한 입 먹고 싶어.'],tired:['조금만 쉴래.','눈이 자꾸 감겨…'],lowBond:['옆에 있어도 돼?','나도 같이 놀고 싶어.'],happy:['헤헤, 또 해 줘!','나 지금 좋아!'],pet:['손이 따뜻해.','여기도 쓰다듬어 줘!'],praise:['나 잘했어?','한 번 더 해 볼래!'],hold:['꼭 잡아 줘.','여기 높다!'],play:['같이 뛰자!','이번엔 내가 먼저!'],feed:['냠냠, 맛있어!','천천히 먹을게.'],train:['하나, 둘!','나도 할 수 있어!'],scold:['놀랐어…','살살 해 줘.'],hit:['아야…','그러면 속상해.'],bicker:['나 삐졌어.','조금만 혼자 있을래.'],win:['우리 이겼다!','나 잘했지?'],loss:['다음엔 잘할래.','조금 속상해…'],attack:['간다!','얍!'],skill:['내 힘을 봐!','준비, 얍!'],study_ok:['아, 알겠다!','맞혔어!'],study_wrong:['한 번 더 볼래.','어디가 틀렸지?'],return:['보고 싶었어!','다시 와 줬다!'],evolution_before:['몸이 간질간질해.','나 조금 달라질 것 같아!'],evolution_after:['우와! 나 자랐어!','이제 이것도 할 수 있어!'],goodbye:['잘 지낼게!','가끔 생각해 줘.'],friend:['같이 놀자!','내 옆에 와!'],baby:['작다… 살살 만질래.','내가 옆에 있을게.'],older:['나도 알려 줘!','같이 가도 돼?'],rest:['여기 폭신해.','잠깐 누울래.'],furniture:['이거 재밌다!','여기서 놀래!'],adolescence:['내가 해 볼래.','잠깐만 기다려 줘.']};
 const grown={neutral:['오늘은 뭘 같이 해 볼까?','잠깐 쉬면서 이야기하자.','네가 오니까 심심하지 않네.'],hungry:['배가 고파서 집중이 안 돼.','간식 먹고 다시 놀자.'],tired:['힘을 다 썼어. 잠깐 쉬자.','잘 쉬는 것도 중요하대.'],lowBond:['우리 요즘 같이 논 시간이 적네.','오늘은 내 얘기도 들어 줄래?'],happy:['이럴 때 정말 신나!','너랑 같이 하니까 더 재미있다.'],pet:['쓰다듬어 주니까 마음이 편해져.','조금만 더, 지금 딱 좋아.'],praise:['고마워! 열심히 한 보람이 있네.','다음에도 잘해 보고 싶어.'],hold:['잠깐만 기대고 있을게.','내가 조금 무거워졌지?'],play:['규칙을 정해서 같이 놀자!','이번엔 내가 술래 할게.'],feed:['잘 먹을게! 나눠 주고 싶을 만큼 맛있다.','꼭꼭 씹어서 천천히 먹어야지.'],train:['어제보다 한 번 더 해 볼게.','기본 동작부터 차근차근 하자.'],scold:['말로 해 줘도 알아들을 수 있어.','놀랐어. 잠깐 진정하고 싶어.'],hit:['아파. 그렇게 하지 말아 줘.','나도 기분이 상할 때가 있어.'],bicker:['조금 진정한 다음 이야기하자.','내 마음도 알아줬으면 좋겠어.'],win:['연습한 걸 제대로 써먹었어!','우리 호흡이 잘 맞았네!'],loss:['어디서 틀렸는지 돌아볼래.','아쉽지만 다음에는 더 잘할 거야.'],attack:['빈틈을 찾았어!','지금이야!'],skill:['준비됐어, 잘 봐!','연습한 대로 해 볼게!'],study_ok:['이제 왜 그런지 알겠어!','다음 문제도 차근차근 풀자.'],study_wrong:['풀이를 다시 살펴보자.','틀린 곳을 찾으면 기억에 남을 거야.'],return:['기다렸어. 오늘 있었던 일 들려줄래?','다시 만나서 정말 반가워.'],evolution_before:['이번에는 어떤 모습으로 자랄까?','조금 떨리지만 준비됐어.'],evolution_after:['많이 자랐지? 이제 더 잘할 수 있을 것 같아.','모습이 달라져도 우리가 함께한 건 기억해.'],goodbye:['함께 지낸 시간은 잊지 않을게. 잘 지낼게!','새로운 곳에서도 씩씩하게 지내 볼게. 고마웠어!'],friend:['서로 잘하는 걸 알려 주자.','네 차례야. 내가 기다릴게.'],baby:['아직 아기니까 살살 놀아 주자.','작은 친구가 놀라지 않게 조용히 있을게.'],older:['그 방법 나한테도 알려 줄래?','다음에는 나도 먼저 해 보고 싶어.'],rest:['잠깐 누워서 쉬면 힘이 돌아올 거야.','지금은 쉬는 시간이야.'],furniture:['이걸 다른 방법으로 써 보면 어떨까?','정리까지 하고 놀아야겠다.'],adolescence:['이번에는 내 생각대로 해 보고 싶어.','도움이 필요하면 부를게.']};
 const personal={
  brave:{2:{neutral:['나 오늘 용감했어!','저쪽까지 달려 볼까?','내 꼬리 따뜻하지?'],friend:['나랑 경주하자!','내가 앞에서 갈게!']},3:{neutral:['어려워 보여도 먼저 해 보고 싶어.','넘어져도 다시 일어나면 되지!','오늘은 누굴 도와줄 수 있을까?'],friend:['빨리 가는 것보다 같이 도착하는 게 좋아.','무서우면 내 옆으로 와.']}},
  careful:{2:{neutral:['새잎이 나왔어!','조용히 들어 봐.','꽃 냄새 좋다.'],friend:['같이 꽃 보러 갈래?','천천히 와도 돼.']},3:{neutral:['어제보다 잎이 조금 더 자랐어.','서두르지 않으면 작은 것도 잘 보여.','오늘 본 꽃을 기억해 두고 싶어.'],friend:['네가 좋아하는 것도 같이 찾아보자.','서로 속도를 맞추면 편할 거야.']}},
  wise:{2:{neutral:['저건 왜 반짝여?','별은 몇 개일까?','궁금한 게 또 생겼어.'],friend:['같이 세어 보자!','내가 찾은 거 볼래?']},3:{neutral:['궁금한 걸 하나씩 알아가는 게 좋아.','그림자가 움직이는 이유를 생각해 봤어.','모르는 건 물어보면 되잖아.'],friend:['우리 생각을 하나씩 말해 보자.','너는 어떻게 풀었는지 궁금해.']}},
  kind:{2:{neutral:['물소리 들려?','네 손 잡아도 돼?','오늘도 같이 놀자.'],friend:['내 자리 나눠 줄게.','괜찮아? 옆에 있을게.']},3:{neutral:['같이 웃으면 하루가 더 좋아져.','친구가 조용하면 먼저 물어봐 주고 싶어.','물결을 보고 있으면 마음이 차분해져.'],friend:['네 얘기부터 들어 볼게.','조금 기다려도 괜찮아. 같이 가자.']}}
 };
 const situationVoices={
 brave:{2:{feed:['먹고 힘낼래!','다 먹으면 달리자!'],tired:['씩씩해도 졸려…','조금 쉬고 다시 할래.'],win:['멍… 아니, 이겼다!','내가 지켜 줬어!'],loss:['분하지만 다시 할래.','다음엔 안 넘어질 거야.'],evolution_after:['나 더 씩씩해졌어!','이제 멍멍 말고 말도 해!']},3:{feed:['훈련한 뒤라 더 맛있네.','기운을 채우고 다시 도전해야지.'],tired:['무리하면 내일 못 노니까 쉬어야겠어.','용감한 나도 쉴 때는 쉬어야지.'],win:['앞장선 보람이 있어! 같이 힘내 줘서 고마워.','어려운 상대였는데 포기하지 않길 잘했어.'],loss:['막 달려들기보다 타이밍을 봐야겠어.','속상해도 친구 앞에서는 다시 일어나 볼래.'],evolution_after:['몸도 마음도 더 씩씩해진 것 같아.','이제 작은 친구들을 지켜 주고 싶어.']}},
 careful:{2:{feed:['조금씩 꼭꼭 먹을래.','좋은 냄새가 나!'],tired:['잎사귀도 쉬고 있네.','조용한 데서 쉴래.'],win:['천천히 해도 됐어!','나도 해냈다…!'],loss:['놀랐어. 손 잡아 줘.','다시 해도 괜찮을까?'],evolution_after:['나도 새잎처럼 자랐어!','이제 내 마음을 말할 수 있어.']},3:{feed:['맛을 천천히 느끼면서 먹고 싶어.','먹고 나면 자리를 깨끗이 정리할게.'],tired:['조용히 쉬면서 오늘 일을 생각해 볼래.','햇볕 드는 곳에서 잠깐 쉬어도 될까?'],win:['차근차근 준비한 덕분이야.','긴장했는데 끝까지 해내서 기뻐.'],loss:['다음에는 주변을 더 잘 살펴볼게.','실수한 순간을 천천히 생각해 보고 싶어.'],evolution_after:['자라는 데 시간이 걸렸지만 기다려 줘서 고마워.','작은 새잎도 이렇게 자라나는 거겠지?']}},
 wise:{2:{feed:['이건 무슨 맛일까?','한 번 더 맛보고 싶어!'],tired:['생각을 너무 많이 했나 봐.','꿈에서도 별 볼래.'],win:['내 생각이 맞았어!','빈틈을 찾았어!'],loss:['왜 졌는지 궁금해.','다른 방법도 해 볼래.'],evolution_after:['궁금한 걸 이제 말할 수 있어!','우와, 더 많이 배울래!']},3:{feed:['같은 음식도 씹을수록 맛이 달라지네.','어떻게 만드는지 궁금해졌어.'],tired:['복잡한 생각은 쉬고 나서 다시 해 볼래.','눈을 감으면 오늘 배운 게 떠올라.'],win:['상대의 움직임을 살핀 게 도움이 됐어.','이번에 알아낸 방법을 기억해 둘게.'],loss:['내가 놓친 단서가 있었나 봐.','답을 바로 못 찾아도 다시 생각하면 돼.'],evolution_after:['전에는 몰랐던 것도 하나씩 알아가고 싶어.','몸이 자란 만큼 생각도 넓어지면 좋겠다.']}},
 kind:{2:{feed:['같이 먹으면 더 좋아.','맛있다! 너도 먹었어?'],tired:['옆에서 같이 쉴래?','조용한 물소리 듣고 싶어.'],win:['우리 둘 다 잘했어!','네가 응원해서 힘났어.'],loss:['조금 안아 줘.','괜찮다고 말해 줘…'],evolution_after:['고맙다고 말하고 싶었어!','내 목소리 들려?']},3:{feed:['챙겨 줘서 고마워. 너도 식사 잊지 마.','좋아하는 음식은 함께 나누고 싶어.'],tired:['오늘은 옆에서 조용히 쉬고 싶어.','조금 쉬면 다시 웃을 힘이 생기겠지.'],win:['끝까지 응원해 준 덕분이야.','이겼지만 상대도 열심히 했네.'],loss:['속상한 마음이 가라앉을 때까지 같이 있어 줘.','한 번 졌다고 우리가 못하는 건 아니잖아.'],evolution_after:['받았던 다정함을 다른 친구에게도 나눠 줄래.','자라도 네 곁에 있으면 마음이 편해.']}}
 };
 for(const [id,stages] of Object.entries(situationVoices))for(const [s,contexts] of Object.entries(stages))Object.assign(personal[id][s],contexts);
 const aliases={talk:'neutral',food:'feed',victory:'win',defeat:'loss',lie:'rest',sleep:'tired',interact:'friend'};
 function context(p,key='auto'){if(key==='auto')key=p.hunger<28?'hungry':p.condition<25?'tired':p.bond<38?'lowBond':p.mood>82?'happy':'neutral';return aliases[key]||key;}
 function line(p,key='auto',override){const s=override??stage(p),k=context(p,key);let pool;
  if(s===0)pool=['hungry','feed'].includes(k)?['😋','🍴❓','🥺']:['tired','rest'].includes(k)?['😴','💤']:['hit','scold','loss','lowBond'].includes(k)?['🥺','😢']:['💗','😊','✨','❣️'];
  else if(s===1){const v=voices[p.starter]||voices.kind;pool=['tired','loss','hit','scold','lowBond','goodbye'].includes(k)?[v[3],v[2]+'…']:v.slice(0,3);}
  else{const base=s===2?young:grown;pool=personal[p.starter]?.[Math.min(s,3)]?.[k]||base[k]||base.neutral;}
  const options=pool.filter(x=>x!==p._lastVoice);const value=options[Math.floor(Math.random()*options.length)]||pool[0];p._lastVoice=value;p.lastDialogueAt=Date.now();p._voice={text:value,context:k,at:Date.now()};return value;
 }
 function cue(p,action,duration=1400){if(!p||stage(p)===0)return;const now=Date.now();p.presentation={action,at:now,until:now+duration};}
 function action(p,key){const map={pet:'interact',praise:'happy',hold:'held',play:'happy',feed:'eat',talk:'interact',train:'attack',scold:'cry',hit:'hurt',bicker:'cry',win:'victory',loss:'defeat',study_ok:'happy',study_wrong:'interact'};if(map[key])cue(p,map[key],key==='feed'?1800:1500);}
 function pose(p){const v=p.presentation,now=Date.now();if(!v||v.until<=now)return null;return v.action==='faint'&&now-v.at>=780?'faint_idle':v.action;}
 const busy=s=>!!(s.hunt?.running||s.battle?.running||s.exploration?.active);
 const roomPets=s=>[s.pets.find(p=>p.id===s.mainPetId),...s.pets.filter(p=>p.id!==s.mainPetId)].filter(Boolean).filter(p=>!p.runaway).slice(0,2);
 function init(s){s.home.petSlots=2;s.independentPets=s.independentPets||[];s.family=s.family||{nextAt:Date.now()+18000};}
 function depart(s,id){if(busy(s))return {ok:false,msg:'활동을 마친 뒤 독립할 수 있어.'};if(s.pets.length<2)return {ok:false,msg:'함께 지낼 펫 한 마리는 남아 있어야 해.'};const p=s.pets.find(p=>p.id===id);if(!p)return {ok:false,msg:'펫을 찾지 못했어.'};const voice=line(p,'goodbye');s.independentPets.push({...JSON.parse(JSON.stringify(p)),independentAt:Date.now(),farewell:voice});s.pets=s.pets.filter(q=>q.id!==id);if(s.mainPetId===id)s.mainPetId=s.pets[0].id;for(const mode of ['hunt','battle'])if(s.ui[mode+'PetId']===id)s.ui[mode+'PetId']=s.mainPetId;s.globalMemories.unshift({t:Date.now(),type:'independence',text:p.name+'이 독립했다. 함께한 성장 기록을 추억첩에 남겼다.'});s.family.nextAt=Date.now()+18000;return {ok:true,pet:p,voice};}
 function choose(s,mode,id){if(busy(s))return false;if(!s.pets.some(p=>p.id===id))return false;s.ui[mode+'PetId']=id;s.mainPetId=id;return true;}
 function tick(s){init(s);if(busy(s)||s.ui.tab!=='home'||Date.now()<s.family.nextAt)return;const pets=roomPets(s);s.family.nextAt=Date.now()+22000+Math.random()*16000;if(pets.some(p=>pose(p)||p.roomAction?.until>Date.now()||Date.now()-(p.lastActionAt||0)<6000))return;
  if(pets.length===1){const p=pets[0];if(stage(p)>0)cue(p,p.condition<35?'lie':p.bond>65?'interact':'idle',2200);return;}
  const [a,b]=pets,sa=stage(a),sb=stage(b),key=sa===0||sb===0?'baby':sa!==sb?'mentor':'friend';
  const pair=[a.starter,b.starter].sort().join(':');const themes={'brave:careful':'불꽃이 앞장서고 새싹이 천천히 따라와요.','brave:wise':'불꽃의 도전과 빛의 생각을 모아요.','brave:kind':'신나게 놀고 서로 숨을 고르게 도와줘요.','careful:wise':'새잎을 살펴보며 작은 변화를 찾아요.','careful:kind':'나란히 앉아 조용히 쉬어요.','kind:wise':'물결을 바라보며 궁금한 것을 나눠요.'};
  const until=Date.now()+6500;a.companion={until,x:.40,y:.73,dir:'right'};b.companion={until,x:.64,y:.73,dir:'left'};
  for(const [p,q] of [[a,b],[b,a]]){const k=stage(q)===0?'baby':stage(p)<stage(q)?'older':'friend';if(stage(p)>0)cue(p,key==='baby'?'interact':key==='mentor'?(stage(p)>stage(q)?'interact':'happy'):pair==='careful:kind'?'lie':'happy',6500);line(p,k);p.relationships=p.relationships||{};p.relationships[q.id]=Math.min(100,(p.relationships[q.id]||0)+.5);}
  s.family.caption=key==='baby'?'작은 친구 곁에서 조심조심 인사해요.':key==='mentor'?'먼저 자란 친구의 동작을 따라 해 봐요.':themes[pair]||'서로 눈을 맞추며 함께 놀아요.';s.family.until=until;
 }
 function render(s,actions,refresh){init(s);const make=(id,parent)=>{let el=document.getElementById(id);if(!el&&parent){el=document.createElement('div');el.id=id;el.className='family-panel';parent.append(el);}return el;};
  const home=make('familyHome',document.getElementById('tab-home'));if(home){home.replaceChildren();const label=document.createElement('small');label.textContent='함께 사는 펫 '+Math.min(2,s.pets.length)+'/2 · 돌볼 펫 선택';home.append(label);for(const p of roomPets(s)){const b=document.createElement('button');b.textContent=p.name+' · '+stage(p)+'단계';b.disabled=busy(s)||p.id===s.mainPetId;b.onclick=()=>{s.mainPetId=p.id;actions.save();refresh();};home.append(b);}if(s.family.until>Date.now()){const caption=document.createElement('p');caption.textContent=s.family.caption;home.append(caption);}}
  for(const mode of ['hunt','battle']){const button=document.getElementById(mode+'Start');if(!button)continue;let label=document.getElementById(mode+'PetPicker');if(!label){label=document.createElement('label');label.id=mode+'PetPicker';label.className='family-picker';button.before(label);}label.replaceChildren();label.append(document.createTextNode('출전할 펫 '));const select=document.createElement('select');for(const p of s.pets.slice(0,2)){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+stage(p)+'단계 · Lv.'+p.level;select.append(o);}const encounter=s[mode];select.value=encounter.running?encounter.petId:s.ui[mode+'PetId']||s.mainPetId;select.disabled=busy(s);select.onchange=()=>{choose(s,mode,select.value);actions.save();refresh();};label.append(select);}
  const cards=document.getElementById('petCards');if(cards&&s.ui.tab==='pets'){for(const [i,p] of s.pets.entries()){const card=cards.children[i];if(!card)continue;const b=document.createElement('button');b.textContent='독립 준비';b.disabled=busy(s)||s.pets.length<2;b.onclick=()=>departureDialog(s,p,actions,refresh);card.append(b);}}
  const album=make('independentAlbum',document.getElementById('tab-pets'));if(album){album.replaceChildren();const h=document.createElement('h3');h.textContent='독립한 친구들의 추억';album.append(h);for(const p of s.independentPets){const item=document.createElement('p');item.textContent=p.name+' · '+p.stage+'단계 · Lv.'+p.level+' — '+p.farewell;album.append(item);}}
 }
 function departureDialog(s,p,actions,refresh){const d=document.createElement('dialog');d.className='pet-farewell';const title=document.createElement('h2');title.textContent=p.name+'의 독립';const note=document.createElement('p');note.textContent='이 집을 떠나 새 생활을 시작해요. 성장과 추억은 독립한 친구들의 추억첩에 남고, 빈자리에 새 펫을 맞이할 수 있어요.';const sprite=document.createElement('div');sprite.className='farewell-sprite';let asset='';for(let n=stage(p);n>=1;n--)if(window.__PET_ASSET_META__?.[p.starter+'_'+n]?.production){asset=window.__ASSET_MANIFEST__?.pets?.[p.starter+'_'+n];break;}if(stage(p)===0){sprite.style.backgroundImage='url(assets/pets/common_stage0_6x12.png)';sprite.style.backgroundSize='600% 1200%';}else if(asset){sprite.style.backgroundImage='url('+asset+')';sprite.style.backgroundSize='600% 2400%';}const cancel=document.createElement('button');cancel.textContent='함께 더 지내기';cancel.onclick=()=>d.close();const yes=document.createElement('button');yes.textContent='독립 응원하기';yes.onclick=()=>{const result=depart(s,p.id);if(!result.ok){note.textContent=result.msg;return;}actions.save();yes.remove();cancel.textContent='추억첩 보기';note.textContent=result.voice;sprite.style.backgroundPositionY=(stage(p)===0?2/11*100:5/23*100)+'%';sprite.classList.add('leaving');actions.sfx?.('reward');setTimeout(()=>{refresh();},1800);};d.append(title,sprite,note,cancel,yes);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();}
 return {stage,line,context,cue,action,pose,busy,roomPets,init,depart,choose,tick,render,
  size:(s,base)=>s===0?base:base*({1:.95,2:1.16,3:1.43,4:1.50}[s]||1.43),
  voiceForMessage(p,msg){if(p._voice?.text===msg&&Date.now()-p._voice.at<5000)return msg;return line(p,Date.now()-(p.lastActionAt||0)<5000?p.lastAction:'auto');}
 };
})();

